config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  root 'patients#index'
  resources :patients do
    resources :encounters
  end

end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
  validates :visit, :admitted_at, presence: true

  belongs_to :patient
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates :first_name, :last_name, :mrn, presence: true
  validates :weight, :height, numericality: true

  has_many :encounters, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  before_action :set_patient
  before_action :set_encounter, only: [:show, :edit, :update, :destroy]

  # GET /encounters
  # GET /encounters.json
  def index
    @encounters = @patient.encounters
  end

  # GET /encounters/1
  # GET /encounters/1.json
  def show
  end

  # GET /encounters/new
  def new
    @encounter = @patient.encounters.build
  end

  # GET /encounters/1/edit
  def edit
  end

  # POST /encounters
  # POST /encounters.json
  def create
    @encounter = Encounter.new(encounter_params)

    respond_to do |format|
      if @encounter.save
        format.html { redirect_to [@patient, @encounter], notice: 'Encounter was successfully created.' }
        format.json { render :show, status: :created, location: [@patient, @encounter] }
      else
        format.html { render :new }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encounters/1
  # PATCH/PUT /encounters/1.json
  def update
    respond_to do |format|
      if @encounter.update(encounter_params)
        format.html { redirect_to [@patient, @encounter], notice: 'Encounter was successfully updated.' }
        format.json { render :show, status: :ok, location: [@patient, @encounter] }
      else
        format.html { render :edit }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encounters/1
  # DELETE /encounters/1.json
  def destroy
    @encounter.destroy
    respond_to do |format|
      format.html { redirect_to patient_encounters_path(@patient), notice: 'Encounter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encounter
      begin
        @encounter = Encounter.find(params[:id])
        unless @patient.encounters.include? @encounter
          logger.info "Got a request for an encouter (#{params[:id]}) "+
                      "that doesn't belong to the patient #{params[:patient_id]}"
          redirect_to root_path
        end
      rescue StandardError => e
        logger.info "Got a request for a non-existing encouter #{params[:id]}"
      end
    end

    def set_patient
      begin
        @patient = Patient.find(params[:patient_id])
      rescue
        logger.info "Got a request for a non-existing patient #{:patient_id}"
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encounter_params
      params
        .require(:encounter)
        .permit(:visit, :admitted_at, :discharged_at, :location, :room, :bed, :patient_id)
    end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patients_path, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :middle_name, :last_name, :weight, :height, :mrn)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/encounters/_form.html.erb
<%= form_for [@patient, @encounter] do |f| %>
  <% if @encounter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@encounter.errors.count, "error") %> prohibited this encounter from being saved:</h2>

      <ul>
      <% @encounter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :visit %><br>
    <%= f.text_field :visit %>
  </div>
  <div class="field">
    <%= f.label :admitted_at %><br>
    <%= f.datetime_select :admitted_at %>
  </div>
  <div class="field">
    <%= f.label :discharged_at %><br>
    <%= f.datetime_select :discharged_at %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :room %><br>
    <%= f.number_field :room %>
  </div>
  <div class="field">
    <%= f.label :bed %><br>
    <%= f.number_field :bed %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.text_field :patient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/encounters/edit.html.erb
<h1>Editing Encounter</h1>
<%= react_component "EncountersEdit", props: { encounter: @encounter, patient: @patient }  %>

app/views/encounters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Encounters</h1>

<table>
  <thead>
    <tr>
      <th>Visit</th>
      <th>Admitted at</th>
      <th>Discharged at</th>
      <th>Location</th>
      <th>Room</th>
      <th>Bed</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encounters.each do |encounter| %>
      <tr>
        <td><%= encounter.visit %></td>
        <td><%= encounter.admitted_at %></td>
        <td><%= encounter.discharged_at %></td>
        <td><%= encounter.location %></td>
        <td><%= encounter.room %></td>
        <td><%= encounter.bed %></td>
        <td><%= encounter.patient %></td>
        <td><%= link_to 'Show', [@patient, encounter] %></td>
        <td><%= link_to 'Edit', edit_patient_encounter_path(@patient, encounter) %></td>
        <td><%= link_to 'Destroy', [@patient, encounter], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encounter', new_patient_encounter_path %>

app/views/encounters/new.html.erb
<%= react_component "EncountersNew", props: { encounter: @encounter, patient: @patient }  %>

app/views/encounters/show.html.erb
<p id="notice"><%= notice %></p>

<%= react_component "EncountersShow", props: { patient: @patient, encounter: @encounter } %>

<%= link_to 'Edit', edit_patient_encounter_path(@patient, @encounter) %> |
<%= link_to 'Back', patient_path(@patient) %>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meditech</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :mrn %><br>
    <%= f.text_field :mrn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<%= react_component("PatientsIndex", props: { patients: @patients }) %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<% if @patient.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

    <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= react_component "PatientsNew", props: { patient: @patient, errors: @patient.errors } %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<%= react_component "PatientsShow", props: { patient: @patient, encounters: @patient.encounters } %>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>